name: "Fortinet Zoho Calendar Sync"
version: "1.1.3"
slug: "fortinet-zoho-sync"
description: "Sincronizzazione automatica scadenze firewall Fortinet con calendario Zoho"
url: "https://github.com/eliaferrarii/Fortinet-Calendar-Sync"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:firewall
panel_title: "Fortinet Scadenze"
startup: application
boot: auto
options: {}
schema: {}
map:
  - config:rw
services:
  - mqtt:want
